### ISSUE TITLE
[hw4] Is `pos-tagger.py` executable?

### ISSUE THREAD

**Issue by imgarylai** [emory-courses/cs571#8]
Hello, 

When I exec the command below:
```
$ python pos-tagger.py data/conll03.eng.trn.gold.tsv data/conll03.eng.dev.gold.tsv
```

It shows this result forever:
```
>> Reading: data/conll03.eng.trn.gold.tsv

```

Do we need to modify something?

**Comment by jdchoi77** [comment]
You need to change the indices since they are using a different format.

**Comment by imgarylai** [comment]
@jdchoi77 Thank you. Yes, I have changed the indices. However, I found the problem. It was because I used `python2.7`. 

`__next__` can only be defined in `python 3` and above. In `python 2`, we have to use `next()`
Therefore, I could not touch the `StopIteration` exception while executing the code! 

I will change to use python 3 and run again.
