### ISSUE TITLE
Dead link and question.

### ISSUE THREAD

**Issue by manineur** [emory-courses/cs571#9]
Hi,

It seems the links to reader and structure in homework5 instructions do not work. Which reader and structure python files is being referred to? Do we need to use reader.py structure.py and dependency parser.py? 

Thanks,
Mani

**Comment by jdchoi77** [comment]
The reader.py and structure.py can be found here:

https://github.com/emorynlp/elit/tree/master/python/elit

You need to write your own dependency parser; dependency_parser.py is a dummy file.

best,

Jinho
